### ISSUE TITLE
stripe-ruby v5 brings breaking changes

### ISSUE THREAD

**Issue by gravitystorm** [stripe-ruby-mock/stripe-ruby-mock#646]
I've been looking into why the test suite is failing, and one of the major items is that stripe-ruby v5 has been released about 7 days ago. This [includes a bunch of breaking changes](https://github.com/stripe/stripe-ruby/wiki/Migration-guide-for-v5), which means this test suite fails. For example, calls in the test suite to [Stripe::Account.all](https://github.com/rebelidealist/stripe-ruby-mock/blob/226bf2d659dceddedb23697610ef2eeb9ab50a87/spec/shared_stripe_examples/account_examples.rb#L18) work fine on v4 but fail on v5. 

stripe-ruby-mock currently has a dependency range of `'stripe', '>= 2.0.3'`. Since there is no upper bound on the contraint, travis will use the latest release i.e. v5, even though the test suite is targetting v4. However, I don't think supporting stripe-ruby v4 and v5 at the same time is practical, given examples like the above.

What do you think is the best approach?

My personal suggestion would be:
* constrain the stripe dependency to be '>= 2.0.3', '< 5' in the gemspec
* get the test suite working on travis again
* make a PR that just changes the stripe dependency to '~> 5.0' along with whichever changes are necessary to get the tests passing
* then release a new version of stripe-ruby-mock

Alternative approaches include just changing the dependency to >= 5 today, even though the tests won't pass. This would then at least indicate that maintaining compatibility to stripe v4 isn't necessary, and we can then fix up the tests.

**Comment by vishnun** [comment]
With the Strong Customer Authentication becoming a mandate this week, support for v5 is rather an urgent need. Our entire test suite depends on stripe-ruby-mock and most of the specs for the new SCA flows are failing due to missing objects like (PaymentMethods, SetupIntents, PaymentIntents, etc).

Any ETA on this?

**Comment by aovertus** [comment]
Any news on the update ? Can I be of any help ? I've mocked our usages of stripe mock waiting it to support v5

**Comment by alexmamonchik** [comment]
thank you very much guys. Let's go by this way:
- constrain the stripe dependency to be '>= 2.0.3', '< 5' in the gemspec

I want to merge as much as possible PRs this week and release `2.5.9`. 

Then  merge PRs with label "will be merged soon" and release it as version `3.0.0`.

thank you for your help. We all use this nice tool.

**Comment by avstudio** [comment]
I'm have this error:

```
 ArgumentError:
       wrong number of arguments (given 3, expected 2)
     # /Users/vucinjo/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/stripe-5.7.0/lib/stripe/errors.rb:70:in `initialize'
```

stripe-ruby-mock 2.5.8

**Comment by perfetti** [comment]
> I'm have this error:
> 
> ```
>  StripeMock.prepare_card_error(:card_declined) 
> ```
> 
> ```
>  ArgumentError:
>        wrong number of arguments (given 3, expected 2)
>      # /Users/vucinjo/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/stripe-5.7.0/lib/stripe/errors.rb:70:in `initialize'
> ```
> 
> stripe-ruby-mock 2.5.8

Here's a monkey patch fix for the meantime till this is actually updated.  It seems like it'll be a big move and take a awhile.

```module StripeMock
  module CardErrors
    def self.add_json_body(error_values)
      error_keys = [:message, :param, :code]

      json_hash = Hash[error_keys.zip error_values]
      json_hash[:type] = 'card_error'
      json_hash[:decline_code] = get_decline_code(json_hash[:code])

      error_code = error_values.delete_at(2)
      error_values.last.merge!(code: error_code, json_body: { error: json_hash }, http_body: { error: json_hash })

      error_values
    end
  end
end```

**Comment by klaustopher** [comment]
Version `3.0.0` of this gem supports Stripe gem >= 5

**Comment by Babbz75** [comment]
I'm using stripe-ruby-mock', '~> 3.0.1' and still getting 

`     ArgumentError:
       wrong number of arguments (given 3, expected 2)
`
from trying to do 

`let(:customer) do
        Stripe::Customer.create({email: 'johnny@appleseed.com',
                                source: StripeMock.create_test_helper.generate_card_token})
      end`

**Comment by hernanat** [comment]
> I'm using stripe-ruby-mock', '~> 3.0.1' and still getting
> 
> ` ArgumentError: wrong number of arguments (given 3, expected 2)`
> from trying to do
> 
> `let(:customer) do Stripe::Customer.create({email: 'johnny@appleseed.com', source: StripeMock.create_test_helper.generate_card_token}) end`

+1

**Comment by crispinheneise** [comment]
Upgrading to 3.1.0.rc2 should fix the ArgumentError. 

```
  gem 'stripe-ruby-mock', '~> 3.1.0.rc2', require: 'stripe_mock'
```

**Comment by notfelineit** [comment]
Also running into this issue. Following @crispinheneise 's suggestion:

`gem list`:
```
stripe (5.32.1)
stripe-ruby-mock (3.1.0.rc2)
```

and still getting:
```
ArgumentError: wrong number of arguments (given 3, expected 2)
```
on 
```ruby
Stripe::InvoiceItem.create({
          customer: stripe_customer_id,
          currency: 'USD',
          unit_amount_decimal: amount,
          quantity: units,
          description: description,
          invoice: invoice_id,
        })
```

**Comment by justinschier** [comment]
Upgrading to 3.1.0.rc2 as per @crispinheneise worked for me!

```
gem 'stripe-ruby-mock', '~> 3.1.0.rc2', require: 'stripe_mock'
```

**Comment by joshuacronemeyer** [comment]
Chiming in, like @justinschier @crispinheneise's suggestion worked for me too. I was doing:

```
  Stripe::Subscription.list(customer: customer_id)
```

And getting the same ArgumentError

**Comment by Aldo510** [comment]
Hello, do someone has an example from **StripeMock.prepare_card_error(:invalid_expiry_month)** method to show me?

**Comment by TastyPi** [comment]
Please don't ask for support in a random issue, either create a new one or ask in the gitter https://gitter.im/rebelidealist/stripe-ruby-mock

I think the original issue here has been fixed, so closing this.

**Comment by lmsilvera** [comment]
> Upgrading to 3.1.0.rc2 should fix the ArgumentError.
> 
> ```
>   gem 'stripe-ruby-mock', '~> 3.1.0.rc2', require: 'stripe_mock'
> ```

I can confirm this worked for me.
